version: '3.5'
services:
  service-grpc-gw:
    restart: on-failure
    depends_on:
      - service-grpc-parser
    build: './service-grpc-gw/'
    ports:
      - '8080:8080'
    networks:
      - quizNetwork

  service-grpc-parser:
    restart: on-failure
    build: './service-grpc-parser/'
    networks:
      - quizNetwork

networks:
  quizNetwork:
    driver: bridge