// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClubsInfoClient is the client API for ClubsInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClubsInfoClient interface {
	GetCompany(ctx context.Context, in *INNCompany, opts ...grpc.CallOption) (*CompanyInfo, error)
}

type clubsInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewClubsInfoClient(cc grpc.ClientConnInterface) ClubsInfoClient {
	return &clubsInfoClient{cc}
}

func (c *clubsInfoClient) GetCompany(ctx context.Context, in *INNCompany, opts ...grpc.CallOption) (*CompanyInfo, error) {
	out := new(CompanyInfo)
	err := c.cc.Invoke(ctx, "/rusprofile_parser.ClubsInfo/getCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClubsInfoServer is the server API for ClubsInfo service.
// All implementations should embed UnimplementedClubsInfoServer
// for forward compatibility
type ClubsInfoServer interface {
	GetCompany(context.Context, *INNCompany) (*CompanyInfo, error)
}

// UnimplementedClubsInfoServer should be embedded to have forward compatible implementations.
type UnimplementedClubsInfoServer struct {
}

func (UnimplementedClubsInfoServer) GetCompany(context.Context, *INNCompany) (*CompanyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}

// UnsafeClubsInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClubsInfoServer will
// result in compilation errors.
type UnsafeClubsInfoServer interface {
	mustEmbedUnimplementedClubsInfoServer()
}

func RegisterClubsInfoServer(s grpc.ServiceRegistrar, srv ClubsInfoServer) {
	s.RegisterService(&ClubsInfo_ServiceDesc, srv)
}

func _ClubsInfo_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(INNCompany)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubsInfoServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusprofile_parser.ClubsInfo/getCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubsInfoServer).GetCompany(ctx, req.(*INNCompany))
	}
	return interceptor(ctx, in, info, handler)
}

// ClubsInfo_ServiceDesc is the grpc.ServiceDesc for ClubsInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClubsInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rusprofile_parser.ClubsInfo",
	HandlerType: (*ClubsInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCompany",
			Handler:    _ClubsInfo_GetCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusprofile_parser.proto",
}
